name: Continuous Integration

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, MySQL ${{ matrix.mysql }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                symfony: ["5.4.*", "^6.0"]
                sylius: ["^1.12"]
                node: ["16.x"]
                mysql: ["5.7", "8.0"]

        env:
            APP_ENV: test
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?serverVersion=${{ matrix.mysql }}"

        steps:
            -
                uses: actions/checkout@v3
                
            -   name: Setup
                run: php configure.php < TEST_ARGUMENTS

            -   name: Build application
                uses: SyliusLabs/BuildTestAppAction@v2.1
                with:
                    build_type: "plugin"
                    cache_key: "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}"
                    cache_restore_key: "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-sylius-${{ matrix.sylius }}-symfony-${{ matrix.symfony }}"
                    e2e: "yes"
                    e2e_js: "yes"
                    database_version: ${{ matrix.mysql }}
                    php_version: ${{ matrix.php }}
                    symfony_version: ${{ matrix.symfony }}

            -
                name: Run Behat JS
                run: vendor/bin/behat --colors --strict -vvv --no-interaction || vendor/bin/behat --colors --strict -vvv --no-interaction --rerun

            -
                name: Upload logs
                uses: actions/upload-artifact@v3
                if: failure()
                with:
                    name: Behat logs
                    path: |
                        etc/build/
                        var/log/
                    if-no-files-found: ignore
